/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZasilRouteImport } from './routes/zasil'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as BazaWiedzyRouteImport } from './routes/baza-wiedzy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EksperymentyIndexRouteImport } from './routes/eksperymenty.index'
import { Route as EksperymentySlugRouteImport } from './routes/eksperymenty.$slug'

const ZasilRoute = ZasilRouteImport.update({
  id: '/zasil',
  path: '/zasil',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const BazaWiedzyRoute = BazaWiedzyRouteImport.update({
  id: '/baza-wiedzy',
  path: '/baza-wiedzy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EksperymentyIndexRoute = EksperymentyIndexRouteImport.update({
  id: '/eksperymenty/',
  path: '/eksperymenty/',
  getParentRoute: () => rootRouteImport,
} as any)
const EksperymentySlugRoute = EksperymentySlugRouteImport.update({
  id: '/eksperymenty/$slug',
  path: '/eksperymenty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baza-wiedzy': typeof BazaWiedzyRoute
  '/kontakt': typeof KontaktRoute
  '/zasil': typeof ZasilRoute
  '/eksperymenty/$slug': typeof EksperymentySlugRoute
  '/eksperymenty/': typeof EksperymentyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baza-wiedzy': typeof BazaWiedzyRoute
  '/kontakt': typeof KontaktRoute
  '/zasil': typeof ZasilRoute
  '/eksperymenty/$slug': typeof EksperymentySlugRoute
  '/eksperymenty': typeof EksperymentyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baza-wiedzy': typeof BazaWiedzyRoute
  '/kontakt': typeof KontaktRoute
  '/zasil': typeof ZasilRoute
  '/eksperymenty/$slug': typeof EksperymentySlugRoute
  '/eksperymenty/': typeof EksperymentyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baza-wiedzy'
    | '/kontakt'
    | '/zasil'
    | '/eksperymenty/$slug'
    | '/eksperymenty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baza-wiedzy'
    | '/kontakt'
    | '/zasil'
    | '/eksperymenty/$slug'
    | '/eksperymenty'
  id:
    | '__root__'
    | '/'
    | '/baza-wiedzy'
    | '/kontakt'
    | '/zasil'
    | '/eksperymenty/$slug'
    | '/eksperymenty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BazaWiedzyRoute: typeof BazaWiedzyRoute
  KontaktRoute: typeof KontaktRoute
  ZasilRoute: typeof ZasilRoute
  EksperymentySlugRoute: typeof EksperymentySlugRoute
  EksperymentyIndexRoute: typeof EksperymentyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zasil': {
      id: '/zasil'
      path: '/zasil'
      fullPath: '/zasil'
      preLoaderRoute: typeof ZasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baza-wiedzy': {
      id: '/baza-wiedzy'
      path: '/baza-wiedzy'
      fullPath: '/baza-wiedzy'
      preLoaderRoute: typeof BazaWiedzyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksperymenty/': {
      id: '/eksperymenty/'
      path: '/eksperymenty'
      fullPath: '/eksperymenty/'
      preLoaderRoute: typeof EksperymentyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksperymenty/$slug': {
      id: '/eksperymenty/$slug'
      path: '/eksperymenty/$slug'
      fullPath: '/eksperymenty/$slug'
      preLoaderRoute: typeof EksperymentySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BazaWiedzyRoute: BazaWiedzyRoute,
  KontaktRoute: KontaktRoute,
  ZasilRoute: ZasilRoute,
  EksperymentySlugRoute: EksperymentySlugRoute,
  EksperymentyIndexRoute: EksperymentyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
